(function(){
"use strict";
const KEY="secpack-lang", SUPPORTED=["en","fa","ar"];

/* Shared EN → FA / AR vocabulary for all public pages.
   Page-specific text is translated here so the site does not depend on
   Google Translate or an external translation service. */
const D={
"Home":["خانه","الرئيسية"],"Products":["محصولات","المنتجات"],"Online Store":["فروشگاه آنلاین","المتجر الإلكتروني"],"Company":["شرکت","الشركة"],"For Manufacturers":["برای تولیدکنندگان","للمصنعين"],"Knowledge Center":["مرکز دانش","مركز المعرفة"],"Resources":["منابع","المصادر"],"Contact":["تماس","اتصل بنا"],
"Contact SEC PACK":["تماس با SEC PACK","اتصل بـ SEC PACK"],"Explore":["بخش‌های سایت","استكشف"],"Connect":["ارتباط","تواصل"],"Legal":["حقوقی","قانوني"],"Business":["کسب‌وکار","الأعمال"],"Partners":["شرکا","الشركاء"],"Manufacturers":["تولیدکنندگان","المصنعون"],
"International Trade & Sourcing":["تجارت بین‌الملل و تأمین","التجارة الدولية والتوريد"],"International Trade · Sourcing · Procurement":["تجارت بین‌الملل · تأمین · خرید","التجارة الدولية · التوريد · المشتريات"],"International sourcing, procurement and trade support for professional B2B customers.":["تأمین بین‌المللی، خرید و پشتیبانی تجارت برای مشتریان حرفه‌ای B2B.","التوريد الدولي والمشتريات ودعم التجارة للعملاء المحترفين في قطاع B2B."],
"SEC PACK · COMPANY PROFILE":["SEC PACK · معرفی شرکت","SEC PACK · نبذة عن الشركة"],"SEC PACK · PRODUCT":["SEC PACK · محصول","SEC PACK · المنتج"],"SEC PACK KNOWLEDGE CENTER":["مرکز دانش SEC PACK","مركز معرفة SEC PACK"],"RESOURCE CENTER":["مرکز منابع","مركز الموارد"],"SEC PACK NETWORK":["شبکه SEC PACK","شبكة SEC PACK"],
"PRODUCT PORTFOLIO":["سبد محصولات","محفظة المنتجات"],"PRODUCT AREAS":["حوزه‌های محصول","مجالات المنتجات"],"PRODUCT FOCUS":["تمرکز محصول","تركيز المنتجات"],"CURRENT PRODUCT AREAS":["حوزه‌های فعلی محصول","مجالات المنتجات الحالية"],
"Materials selected for professional printing, packaging and converting.":["مواد منتخب برای چاپ، بسته‌بندی و تبدیل حرفه‌ای.","مواد مختارة للطباعة والتغليف والتحويل الاحترافي."],
"SEC PACK develops its portfolio around clear specifications, industrial applications and dependable supply.":["SEC PACK سبد محصولات خود را بر اساس مشخصات روشن، کاربردهای صنعتی و تأمین قابل اتکا توسعه می‌دهد.","تطوّر SEC PACK محفظتها حول المواصفات الواضحة والتطبيقات الصناعية والتوريد الموثوق."],
"A4 Copy Paper":["کاغذ تحریر A4","ورق نسخ A4"],"Lamination Films":["فیلم‌های لمینیشن","أفلام التصفيح"],"Water-Based Adhesives":["چسب‌های پایه آب","مواد لاصقة مائية"],"Packaging Materials":["مواد بسته‌بندی","مواد التغليف"],
"A4 copy paper sourcing for professional B2B buyers: 210 × 297 mm, 75–80 GSM programs, 500 sheets per ream, OEM and private-label supply options.":["تأمین کاغذ تحریر A4 برای خریداران حرفه‌ای B2B: ابعاد 210 × 297 میلی‌متر، برنامه‌های 75 تا 80 گرم، 500 برگ در هر ریم و گزینه‌های OEM و برند اختصاصی.","توريد ورق نسخ A4 للمشترين المحترفين B2B: مقاس 210 × 297 مم، برامج 75–80 غ/م²، 500 ورقة لكل رزمة، وخيارات OEM والعلامة الخاصة."],
"B2B sourcing for BOPP, PET and MPET lamination films for paper, board, printing and packaging applications.":["تأمین B2B فیلم‌های لمینیشن BOPP، PET و MPET برای کاغذ، مقوا، چاپ و بسته‌بندی.","توريد B2B لأفلام التصفيح BOPP وPET وMPET لتطبيقات الورق والكرتون والطباعة والتغليف."],
"Water-based adhesive sourcing for dry lamination of film to paper, board and packaging substrates, with technical documentation where applicable.":["تأمین چسب پایه آب برای لمینیشن خشک فیلم روی کاغذ، مقوا و بسترهای بسته‌بندی، همراه با مستندات فنی در صورت وجود.","توريد مواد لاصقة مائية للتصفيح الجاف بين الأفلام والورق والكرتون ومواد التغليف، مع الوثائق الفنية عند توفرها."],
"Specification-led sourcing of packaging materials for printers, converters and manufacturers through international procurement programs.":["تأمین مشخصات‌محور مواد بسته‌بندی برای چاپخانه‌ها، مبدل‌ها و تولیدکنندگان از طریق برنامه‌های خرید بین‌المللی.","توريد مواد تغليف وفق المواصفات للطابعين والمحوّلين والمصنعين من خلال برامج مشتريات دولية."],
"View A4 specifications":["مشاهده مشخصات A4","عرض مواصفات A4"],"View film specifications":["مشاهده مشخصات فیلم","عرض مواصفات الأفلام"],"View adhesive specifications":["مشاهده مشخصات چسب","عرض مواصفات المواد اللاصقة"],"View packaging materials":["مشاهده مواد بسته‌بندی","عرض مواد التغليف"],"Scientific product guide":["راهنمای علمی محصول","الدليل العلمي للمنتج"],"Add to cart":["افزودن به سبد","أضف إلى السلة"],"Cart:":["سبد:","السلة:"],"· View order":["· مشاهده سفارش","· عرض الطلب"],
"Need more technical information?":["اطلاعات فنی بیشتری نیاز دارید؟","هل تحتاج إلى مزيد من المعلومات الفنية؟"],"Visit the SEC PACK Knowledge Center for deeper material and application guidance. If you have a technical question, send it to us and our team can respond online.":["برای راهنمایی عمیق‌تر درباره مواد و کاربردها به مرکز دانش SEC PACK مراجعه کنید. اگر سؤال فنی دارید، آن را برای ما ارسال کنید تا تیم ما پاسخ دهد.","زر مركز معرفة SEC PACK للحصول على إرشادات أعمق حول المواد والتطبيقات. إذا كان لديك سؤال فني، أرسله إلينا ليجيب فريقنا عبر الإنترنت."],"Go to Knowledge Center →":["رفتن به مرکز دانش →","الانتقال إلى مركز المعرفة →"],"Ask a technical question →":["پرسش فنی →","طرح سؤال فني →"],
"International sourcing built around real procurement requirements.":["تأمین بین‌المللی بر پایه نیازهای واقعی خرید.","التوريد الدولي المبني على احتياجات المشتريات الفعلية."],"Start a business discussion":["شروع گفت‌وگوی تجاری","بدء مناقشة تجارية"],"For manufacturers & export partners":["برای تولیدکنندگان و شرکای صادراتی","للمصنعين وشركاء التصدير"],"WHAT WE DO":["ما چه می‌کنیم","ماذا نفعل"],"A practical bridge between demand and supply.":["پل عملی میان تقاضا و عرضه.","حلقة وصل عملية بين الطلب والعرض."],"Source":["تأمین","التوريد"],"Evaluate":["ارزیابی","التقييم"],"Coordinate":["هماهنگی","التنسيق"],"Identify suitable manufacturers and export partners against product, quality, packaging, quantity and destination requirements.":["تولیدکنندگان و شرکای صادراتی مناسب را بر اساس محصول، کیفیت، بسته‌بندی، مقدار و مقصد شناسایی می‌کنیم.","نحدد المصنعين وشركاء التصدير المناسبين وفق متطلبات المنتج والجودة والتغليف والكمية والوجهة."],"Compare technical specifications, documentation, production capability, commercial terms and practical delivery considerations.":["مشخصات فنی، مستندات، توان تولید، شرایط تجاری و ملاحظات عملی تحویل را مقایسه می‌کنیم.","نقارن المواصفات الفنية والوثائق والقدرة الإنتاجية والشروط التجارية واعتبارات التسليم العملية."],"Structure RFQs, clarify specifications, support negotiation and coordinate the purchasing process through agreed commercial terms.":["استعلام‌های قیمت را ساختاربندی، مشخصات را شفاف، مذاکرات را پشتیبانی و فرایند خرید را بر اساس شرایط توافق‌شده هماهنگ می‌کنیم.","ننظم طلبات عروض الأسعار، ونوضح المواصفات، وندعم التفاوض، وننسق عملية الشراء وفق الشروط التجارية المتفق عليها."],
"HOW WE CREATE VALUE":["چگونه ارزش ایجاد می‌کنیم","كيف نصنع القيمة"],"Requirement-led procurement, with fewer assumptions.":["خرید مبتنی بر نیاز، با حداقل فرضیات.","مشتريات قائمة على المتطلبات، مع أقل قدر من الافتراضات."],"Start with the application":["از کاربرد شروع کنید","ابدأ بالتطبيق"],"Compare on like-for-like terms":["مقایسه بر مبنای شرایط هم‌سطح","قارن على أساس متكافئ"],"Confirm before commitment":["پیش از تعهد تأیید کنید","أكد قبل الالتزام"],
"OUR WORKFLOW":["فرایند کاری ما","آلية عملنا"],"Clear requirements. Documented decisions.":["نیازهای روشن. تصمیم‌های مستند.","متطلبات واضحة. قرارات موثقة."],"Requirement and application":["نیاز و کاربرد","المتطلب والتطبيق"],"Supplier and product screening":["غربالگری تأمین‌کننده و محصول","فحص المورد والمنتج"],"Technical and commercial review":["بررسی فنی و تجاری","المراجعة الفنية والتجارية"],"Quotation, terms and delivery planning":["برنامه‌ریزی قیمت، شرایط و تحویل","التخطيط للعرض والشروط والتسليم"],"Order coordination and documentation":["هماهنگی سفارش و مستندات","تنسيق الطلب والوثائق"],
"BUSINESS PRINCIPLES":["اصول کسب‌وکار","مبادئ العمل"],"What partners can expect.":["آنچه شرکا می‌توانند انتظار داشته باشند.","ما يمكن للشركاء توقعه."],"Specification discipline":["انضباط در مشخصات","الانضباط في المواصفات"],"Commercial clarity":["شفافیت تجاری","الوضوح التجاري"],"Confidentiality by design":["محرمانگی از ابتدا","السرية بحكم التصميم"],"Long-term supply":["تأمین بلندمدت","التوريد طويل الأجل"],
"FOR MANUFACTURERS · EXPORT PARTNERS":["برای تولیدکنندگان · شرکای صادراتی","للمصنعين · شركاء التصدير"],"A structured route to long-term B2B supply.":["مسیر ساختاریافته برای تأمین بلندمدت B2B.","مسار منظم للتوريد طويل الأجل في قطاع B2B."],"Discuss cooperation":["گفت‌وگوی همکاری","ناقش التعاون"],"Company profile":["معرفی شرکت","نبذة عن الشركة"],"WHAT AN EXPORT TEAM CAN EXPECT":["انتظارات از تیم صادرات","ما يمكن لفريق التصدير توقعه"],"A clear commercial brief before detailed discussion.":["شرح تجاری روشن پیش از گفت‌وگوی جزئی.","موجز تجاري واضح قبل المناقشة التفصيلية."],"Defined demand":["تقاضای مشخص","طلب محدد"],"Technical review":["بررسی فنی","مراجعة فنية"],"Commercial coordination":["هماهنگی تجاری","تنسيق تجاري"],"WHAT WE LOOK FOR":["آنچه به دنبال آن هستیم","ما نبحث عنه"],"Capability, documentation and communication that support a serious export relationship.":["توانمندی، مستندات و ارتباطی که از یک رابطه صادراتی جدی پشتیبانی کند.","قدرة ووثائق وتواصل يدعم علاقة تصدير جادة."],"Product fit":["تناسب محصول","ملاءمة المنتج"],"Supply capability":["توان تأمین","قدرة التوريد"],"Documentation":["مستندات","الوثائق"],"HOW WE WORK":["چگونه کار می‌کنیم","كيف نعمل"],"A structured first conversation saves time.":["یک گفت‌وگوی اولیه ساختاریافته در زمان صرفه‌جویی می‌کند.","المحادثة الأولى المنظمة توفر الوقت."],"CURRENT PRODUCT AREAS":["حوزه‌های فعلی محصول","مجالات المنتجات الحالية"],"Opportunities across paper and packaging materials.":["فرصت‌ها در حوزه کاغذ و مواد بسته‌بندی.","فرص في الورق ومواد التغليف."],"COMMERCIAL DISCIPLINE":["انضباط تجاری","الانضباط التجاري"],"We confirm the details before commitment.":["پیش از تعهد، جزئیات را تأیید می‌کنیم.","نؤكد التفاصيل قبل الالتزام."],"EXPORT SALES":["فروش صادراتی","مبيعات التصدير"],"Send your product and export proposal.":["پیشنهاد محصول و صادرات خود را ارسال کنید.","أرسل عرض المنتج والتصدير الخاص بك."],
"SPECIFICATION":["مشخصات","المواصفات"],"Built around the buyer's actual requirement.":["بر پایه نیاز واقعی خریدار.","مبني على متطلبات المشتري الفعلية."],"Core specification":["مشخصات اصلی","المواصفات الأساسية"],"Application":["کاربرد","التطبيق"],"Format / process":["فرمت / فرایند","التنسيق / العملية"],"Technical requirement":["نیاز فنی","المتطلب الفني"],"Supply program":["برنامه تأمین","برنامج التوريد"],"PROCUREMENT":["خرید","المشتريات"],"What we need to quote accurately.":["اطلاعات لازم برای قیمت‌گذاری دقیق.","ما نحتاجه لتقديم عرض دقيق."],"Technical specification":["مشخصات فنی","المواصفات الفنية"],"Quantity and packaging":["مقدار و بسته‌بندی","الكمية والتغليف"],"Destination and delivery terms":["مقصد و شرایط تحویل","الوجهة وشروط التسليم"],"Commercial and documentation requirements":["النیازهای تجاری و مستنداتی","المتطلبات التجارية والوثائق"],"START A SUPPLY REQUEST":["شروع درخواست تأمین","ابدأ طلب التوريد"],"Need this product for a B2B program?":["این محصول را برای برنامه B2B نیاز دارید؟","هل تحتاج هذا المنتج لبرنامج B2B؟"],"Request a quotation":["درخواست قیمت","طلب عرض سعر"],"Request / Order":["درخواست / سفارش","طلب / طلب شراء"],"Discuss specifications":["گفت‌وگوی مشخصات","مناقشة المواصفات"],
"ONLINE SUPPLY CENTER":["مرکز تأمین آنلاین","مركز التوريد عبر الإنترنت"],"Prepare a B2B order request online.":["درخواست سفارش B2B را آنلاین آماده کنید.","جهّز طلب شراء B2B عبر الإنترنت."],"Select products and quantities here. This is an inquiry-preparation tool, not a live payment checkout; final price, availability, specifications and delivery terms are confirmed directly by SEC PACK.":["محصولات و مقدار را اینجا انتخاب کنید. این ابزار برای آماده‌سازی درخواست است، نه پرداخت آنلاین؛ قیمت نهایی، موجودی، مشخصات و شرایط تحویل مستقیماً توسط SEC PACK تأیید می‌شود.","اختر المنتجات والكميات هنا. هذه أداة لإعداد الطلب وليست للدفع المباشر؛ يتم تأكيد السعر النهائي والتوفر والمواصفات وشروط التسليم مباشرة من SEC PACK."],"Order-ready supply categories":["دسته‌های آماده سفارش","فئات التوريد الجاهزة للطلب"],"Add to order":["افزودن به سفارش","أضف إلى الطلب"],"Film solutions for paper and board lamination":["راهکارهای فیلم برای لمینیشن کاغذ و مقوا","حلول أفلام لتصفيح الورق والكرتون"],"Dry-lamination applications · TDS/COA where applicable":["کاربردهای لمینیشن خشک · TDS/COA در صورت وجود","تطبيقات التصفيح الجاف · TDS/COA عند توفرها"],"Specification-led sourcing for converters and manufacturers":["تأمین مشخصات‌محور برای مبدل‌ها و تولیدکنندگان","توريد وفق المواصفات للمحوّلين والمصنعين"],"Your online order":["سفارش آنلاین شما","طلبك عبر الإنترنت"],"Final quotation:":["قیمت نهایی:","عرض السعر النهائي:"],"SEC PACK will confirm price, availability, specifications, delivery terms and payment method before order acceptance.":["SEC PACK پیش از پذیرش سفارش، قیمت، موجودی، مشخصات، شرایط تحویل و روش پرداخت را تأیید می‌کند.","ستؤكد SEC PACK السعر والتوفر والمواصفات وشروط التسليم وطريقة الدفع قبل قبول الطلب."],"Preferred payment method":["روش پرداخت ترجیحی","طريقة الدفع المفضلة"],"Bank transfer":["حواله بانکی","تحويل مصرفي"],"Local online payment":["پرداخت آنلاین محلی","دفع محلي عبر الإنترنت"],"International payment":["پرداخت بین‌المللی","دفع دولي"],"Prepare order request":["آماده‌سازی درخواست سفارش","إعداد طلب الشراء"],"B2B CHECKOUT":["ثبت سفارش B2B","إتمام طلب B2B"],"Online ordering, with commercial confirmation.":["سفارش آنلاین، با تأیید تجاری.","الطلب عبر الإنترنت مع تأكيد تجاري."],
"CONTACT SEC PACK":["تماس با SEC PACK","اتصل بـ SEC PACK"],"Start with your exact requirement.":["از نیاز دقیق خود شروع کنید.","ابدأ بمتطلباتك الدقيقة."],"For a useful first discussion, provide the product, application, specification, approximate quantity and target market.":["برای یک گفت‌وگوی اولیه مفید، محصول، کاربرد، مشخصات، مقدار تقریبی و بازار هدف را اعلام کنید.","لبدء مناقشة مفيدة، اذكر المنتج والتطبيق والمواصفات والكمية التقريبية والسوق المستهدف."],"WHAT TO INCLUDE":["چه اطلاعاتی وارد کنیم","ما الذي يجب تضمينه"],"A clear brief gets a clearer sourcing response.":["شرح روشن، پاسخ تأمین روشن‌تری ایجاد می‌کند.","الموجز الواضح يؤدي إلى استجابة توريد أوضح."],"Product and application":["محصول و کاربرد","المنتج والتطبيق"],"Required quantity and packaging":["مقدار موردنیاز و بسته‌بندی","الكمية والتغليف المطلوبان"],"Destination market and timing":["بازار مقصد و زمان‌بندی","سوق الوجهة والجدول الزمني"],"Name":["نام","الاسم"],"Product / Requirement":["محصول / نیاز","المنتج / المتطلب"],"Message":["پیام","الرسالة"],"Prepare Inquiry":["آماده‌سازی درخواست","إعداد الاستفسار"],"BUSINESS COOPERATION":["همکاری تجاری","التعاون التجاري"],"What makes an inquiry commercially useful?":["چه چیزی یک درخواست را از نظر تجاری مفید می‌کند؟","ما الذي يجعل الاستفسار مفيدًا تجاريًا؟"],"Buyers":["خریداران","المشترون"],"Manufacturers":["تولیدکنندگان","المصنعون"],"Confidentiality":["محرمانگی","السرية"],"B2B COOPERATION":["همکاری B2B","تعاون B2B"],"Looking for a manufacturer or supply partner?":["به دنبال تولیدکننده یا شریک تأمین هستید؟","هل تبحث عن مصنع أو شريك توريد؟"],
"Privacy & Data Handling":["حریم خصوصی و مدیریت داده","الخصوصية ومعالجة البيانات"],"Public privacy information for SEC PACK website visitors and B2B inquiries.":["اطلاعات عمومی حریم خصوصی برای بازدیدکنندگان سایت و درخواست‌های B2B.","معلومات الخصوصية العامة لزوار موقع SEC PACK واستفسارات B2B."],"PUBLIC WEBSITE":["وب‌سایت عمومی","الموقع العام"],"Designed to minimize unnecessary data exposure.":["طراحی‌شده برای کاهش افشای غیرضروری داده‌ها.","مصمم لتقليل كشف البيانات غير الضروري."],"Public website":["وب‌سایت عمومی","الموقع العام"],"Local browser data":["داده‌های محلی مرورگر","بيانات المتصفح المحلية"],"Confidential business data":["داده‌های محرمانه تجاری","بيانات الأعمال السرية"],"Future ordering":["سفارش‌دهی آینده","الطلبات المستقبلية"],"Terms of Use":["شرایط استفاده","شروط الاستخدام"],"General website and B2B supply request terms for SEC PACK.":["شرایط عمومی استفاده از وب‌سایت و درخواست تأمین B2B برای SEC PACK.","الشروط العامة للموقع وطلبات التوريد B2B لدى SEC PACK."],"Clear expectations for product and sourcing inquiries.":["انتظارات روشن برای درخواست‌های محصول و تأمین.","توقعات واضحة لاستفسارات المنتجات والتوريد."],"Product information":["اطلاعات محصول","معلومات المنتج"],"Quotations":["قیمت‌ها و پیشنهادهای تجاری","عروض الأسعار"],"Third-party services":["خدمات شخص ثالث","خدمات الأطراف الثالثة"],"Accuracy":["دقت اطلاعات","دقة المعلومات"],
"SEC PACK KNOWLEDGE CENTER":["مرکز دانش SEC PACK","مركز معرفة SEC PACK"],"Practical knowledge for better sourcing and purchasing decisions.":["دانش کاربردی برای تصمیم‌های بهتر در تأمین و خرید.","معرفة عملية لاتخاذ قرارات أفضل في التوريد والشراء."],"Independent-style educational content from SEC PACK covering product specifications, supplier evaluation and international procurement. Commercial offers are always confirmed separately.":["محتوای آموزشی مستقل‌گونه SEC PACK درباره مشخصات محصول، ارزیابی تأمین‌کننده و خرید بین‌المللی. پیشنهادهای تجاری همیشه جداگانه تأیید می‌شوند.","محتوى تعليمي من SEC PACK حول مواصفات المنتجات وتقييم الموردين والمشتريات الدولية. يتم دائمًا تأكيد العروض التجارية بشكل منفصل."],"A4 COPY PAPER":["کاغذ تحریر A4","ورق نسخ A4"],"75 GSM vs 80 GSM: what actually changes?":["75 گرم در برابر 80 گرم: چه چیزی واقعاً تغییر می‌کند؟","75 مقابل 80 غ/م²: ما الذي يتغير فعليًا؟"],"Weight":["وزن","الوزن"],"Handling":["نحوه کار و جابه‌جایی","المناولة"],"Printer performance":["عملکرد چاپگر","أداء الطابعة"],"SUPPLIER EVALUATION":["ارزیابی تأمین‌کننده","تقييم المورد"],"A professional RFQ should define the product before asking for price.":["یک RFQ حرفه‌ای باید پیش از درخواست قیمت، محصول را دقیق تعریف کند.","يجب أن يحدد طلب عرض السعر المهني المنتج قبل طلب السعر."],"Technical specification":["مشخصات فنی","المواصفات الفنية"],"Commercial specification":["مشخصات تجاری","المواصفات التجارية"],"Evidence":["شواهد و مستندات","الأدلة"],"LANDED COST":["هزینه نهایی تحویل","التكلفة النهائية عند الوصول"],"Factory price is not the same as delivered cost.":["قیمت کارخانه با هزینه تحویل‌شده یکسان نیست.","سعر المصنع ليس هو نفسه تكلفة التسليم."],"Product":["محصول","المنتج"],"Origin logistics":["لجستیک مبدأ","لوجستيات المنشأ"],"International transport":["حمل‌ونقل بین‌المللی","النقل الدولي"],"Destination":["مقصد","الوجهة"],"LAMINATION & ADHESIVES":["لمینیشن و چسب‌ها","التصفيح والمواد اللاصقة"],"Specification checklist before requesting a quotation.":["چک‌لیست مشخصات پیش از درخواست قیمت.","قائمة تحقق للمواصفات قبل طلب عرض السعر."],"Lamination film":["فیلم لمینیشن","فيلم التصفيح"],"Water-based adhesive":["چسب پایه آب","المادة اللاصقة المائية"],"FAQ":["سؤالات متداول","الأسئلة الشائعة"],"Common procurement questions":["پرسش‌های رایج خرید","أسئلة المشتريات الشائعة"],"75 GSM or 80 GSM?":["75 گرم یا 80 گرم؟","75 أم 80 غ/م²؟"],"How should suppliers be compared?":["تأمین‌کنندگان چگونه مقایسه شوند؟","كيف تتم مقارنة الموردين؟"],"Why request samples?":["چرا نمونه درخواست کنیم؟","لماذا نطلب عينات؟"],"What makes a long-term supply program?":["چه چیزی یک برنامه تأمین بلندمدت می‌سازد؟","ما الذي يجعل برنامج التوريد طويل الأجل ناجحًا؟"],"USE THE KNOWLEDGE":["از دانش استفاده کنید","استخدم المعرفة"],"Have a specific sourcing requirement?":["نیاز مشخصی برای تأمین دارید؟","هل لديك متطلب توريد محدد؟"],"Discuss a requirement":["گفت‌وگوی درباره نیاز","ناقش متطلبًا"],
"HOW WE WORK":["چگونه کار می‌کنیم","كيف نعمل"],"Practical information for a disciplined procurement process.":["اطلاعات کاربردی برای فرایند خرید منظم و دقیق.","معلومات عملية لعملية مشتريات منضبطة."],"Product Specifications":["مشخصات محصول","مواصفات المنتج"],"Technical Documentation":["مستندات فنی","الوثائق الفنية"],"Supplier Evaluation":["ارزیابی تأمین‌کننده","تقييم المورد"],"RFQ Preparation":["آماده‌سازی RFQ","إعداد طلب عرض السعر"],"Quality Review":["بررسی کیفیت","مراجعة الجودة"],"Procurement Workflow":["فرایند خرید","سير عمل المشتريات"],
"Register for Technical Updates":["ثبت‌نام برای دریافت اطلاعات فنی","التسجيل للحصول على التحديثات الفنية"],"Register your business profile":["ثبت اطلاعات حرفه‌ای","تسجيل ملفك المهني"],"Register and stay connected":["ثبت‌نام و ارتباط با SEC PACK","سجّل وابقَ على تواصل"],"Register for technical solutions and new product updates.":["برای راهکارهای فنی و محصولات جدید ثبت‌نام کنید.","سجّل للحصول على الحلول الفنية وتحديثات المنتجات الجديدة."],"Tell us a little about your professional activity. We will share useful technical information and, if you choose, relevant new products and business updates.":["کمی درباره فعالیت حرفه‌ای خود بگویید. اطلاعات فنی کاربردی و در صورت تمایل محصولات و به‌روزرسانی‌های تجاری مرتبط را با شما به اشتراک می‌گذاریم.","أخبرنا قليلًا عن نشاطك المهني. سنشاركك معلومات فنية مفيدة، وإذا اخترت، منتجات جديدة وتحديثات تجارية ذات صلة."],"Full name":["نام و نام خانوادگی","الاسم الكامل"],"Company":["شرکت","الشركة"],"Country / City":["کشور / شهر","الدولة / المدينة"],"Job title":["عنوان شغلی","المسمى الوظيفي"],"Business activity":["فعالیت کسب‌وکار","نشاط الأعمال"],"Product / technical interest":["محصول / زمینه فنی موردنظر","المنتج / الاهتمام الفني"],"Mobile / WhatsApp":["موبایل / واتساپ","الجوال / واتساب"],"Email":["ایمیل","البريد الإلكتروني"],"Company website":["وب‌سایت شرکت","موقع الشركة"],"Message / requirement":["پیام / نیاز","الرسالة / المتطلب"],"I agree to receive technical information, new product updates and relevant business messages from SEC PACK by email, WhatsApp or SMS.":["موافقم اطلاعات فنی، محصولات جدید و پیام‌های تجاری مرتبط SEC PACK را از طریق ایمیل، واتساپ یا پیامک دریافت کنم.","أوافق على تلقي المعلومات الفنية وتحديثات المنتجات الجديدة والرسائل التجارية ذات الصلة من SEC PACK عبر البريد الإلكتروني أو واتساب أو الرسائل النصية."],"Privacy Policy":["سیاست حفظ حریم خصوصی","سياسة الخصوصية"],"Close":["بستن","إغلاق"]
};

function translateNode(el,lang){
 const raw=(el.textContent||"").replace(/\s+/g," ").trim();
 if(!raw)return;
 if(!el.hasAttribute("data-original-text")) el.setAttribute("data-original-text",raw);
 if(lang==="en"){ el.textContent=el.getAttribute("data-original-text"); return; }
 const v=D[el.getAttribute("data-original-text")||raw];
 if(v && v[lang==="fa"?0:1]) el.textContent=v[lang==="fa"?0:1];
}

function applyExact(lang){
 document.documentElement.lang=lang;
 document.documentElement.dir=(lang==="fa"||lang==="ar")?"rtl":"ltr";
 document.querySelectorAll("[data-lang]").forEach(b=>{
   b.classList.toggle("on",b.dataset.lang===lang);
   b.classList.toggle("active-language",b.dataset.lang===lang);
 });
 document.querySelectorAll("body *").forEach(el=>{
   if(el.children.length===0) translateNode(el,lang);
 });
 if(window.applyPageTranslations) window.applyPageTranslations(lang);
 localStorage.setItem(KEY,lang);
}

function setLanguage(lang){
 lang=SUPPORTED.includes(lang)?lang:"en";
 applyExact(lang);
 if(typeof window.setHomepageLanguage==="function") window.setHomepageLanguage(lang);
}
function init(){
 document.querySelectorAll("[data-lang]").forEach(btn=>{
   btn.addEventListener("click",()=>setLanguage(btn.dataset.lang));
 });
 setLanguage(localStorage.getItem(KEY)||"en");
}
window.secpackSetLanguage=setLanguage;
if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",init,{once:true}); else init();
})();