(function(){
"use strict";
const KEY="secpack-lang", SUPPORTED=["en","fa","ar"];

/* Shared EN → FA / AR vocabulary for all public pages.
   Page-specific text is translated here so the site does not depend on
   Google Translate or an external translation service. */
const D={
"Home":["خانه","الرئيسية"],"Products":["محصولات","المنتجات"],"Online Store":["فروشگاه آنلاین","المتجر الإلكتروني"],"Company":["شرکت","الشركة"],"For Manufacturers":["برای تولیدکنندگان","للمصنعين"],"Knowledge Center":["مرکز دانش","مركز المعرفة"],"Resources":["منابع","المصادر"],"Contact":["تماس","اتصل بنا"],
"Contact SEC PACK":["تماس با SEC PACK","اتصل بـ SEC PACK"],"Explore":["بخش‌های سایت","استكشف"],"Connect":["ارتباط","تواصل"],"Legal":["حقوقی","قانوني"],"Business":["کسب‌وکار","الأعمال"],"Partners":["شرکا","الشركاء"],"Manufacturers":["تولیدکنندگان","المصنعون"],
"International Trade & Sourcing":["تجارت بین‌الملل و تأمین","التجارة الدولية والتوريد"],"International Trade · Sourcing · Procurement":["تجارت بین‌الملل · تأمین · خرید","التجارة الدولية · التوريد · المشتريات"],"International sourcing, procurement and trade support for professional B2B customers.":["تأمین بین‌المللی، خرید و پشتیبانی تجارت برای مشتریان حرفه‌ای B2B.","التوريد الدولي والمشتريات ودعم التجارة للعملاء المحترفين في قطاع B2B."],
"SEC PACK · COMPANY PROFILE":["SEC PACK · معرفی شرکت","SEC PACK · نبذة عن الشركة"],"SEC PACK · PRODUCT":["SEC PACK · محصول","SEC PACK · المنتج"],"SEC PACK KNOWLEDGE CENTER":["مرکز دانش SEC PACK","مركز معرفة SEC PACK"],"RESOURCE CENTER":["مرکز منابع","مركز الموارد"],"SEC PACK NETWORK":["شبکه SEC PACK","شبكة SEC PACK"],
"PRODUCT PORTFOLIO":["سبد محصولات","محفظة المنتجات"],"PRODUCT AREAS":["حوزه‌های محصول","مجالات المنتجات"],"PRODUCT FOCUS":["تمرکز محصول","تركيز المنتجات"],"CURRENT PRODUCT AREAS":["حوزه‌های فعلی محصول","مجالات المنتجات الحالية"],
"Materials selected for professional printing, packaging and converting.":["مواد منتخب برای چاپ، بسته‌بندی و تبدیل حرفه‌ای.","مواد مختارة للطباعة والتغليف والتحويل الاحترافي."],
"SEC PACK develops its portfolio around clear specifications, industrial applications and dependable supply.":["SEC PACK سبد محصولات خود را بر اساس مشخصات روشن، کاربردهای صنعتی و تأمین قابل اتکا توسعه می‌دهد.","تطوّر SEC PACK محفظتها حول المواصفات الواضحة والتطبيقات الصناعية والتوريد الموثوق."],
"A4 Copy Paper":["کاغذ تحریر A4","ورق نسخ A4"],"Lamination Films":["فیلم‌های لمینیشن","أفلام التصفيح"],"Water-Based Adhesives":["چسب‌های پایه آب","مواد لاصقة مائية"],"Packaging Materials":["مواد بسته‌بندی","مواد التغليف"],
"A4 copy paper sourcing for professional B2B buyers: 210 × 297 mm, 75–80 GSM programs, 500 sheets per ream, OEM and private-label supply options.":["تأمین کاغذ تحریر A4 برای خریداران حرفه‌ای B2B: ابعاد 210 × 297 میلی‌متر، برنامه‌های 75 تا 80 گرم، 500 برگ در هر ریم و گزینه‌های OEM و برند اختصاصی.","توريد ورق نسخ A4 للمشترين المحترفين B2B: مقاس 210 × 297 مم، برامج 75–80 غ/م²، 500 ورقة لكل رزمة، وخيارات OEM والعلامة الخاصة."],
"B2B sourcing for BOPP, PET and MPET lamination films for paper, board, printing and packaging applications.":["تأمین B2B فیلم‌های لمینیشن BOPP، PET و MPET برای کاغذ، مقوا، چاپ و بسته‌بندی.","توريد B2B لأفلام التصفيح BOPP وPET وMPET لتطبيقات الورق والكرتون والطباعة والتغليف."],
"Water-based adhesive sourcing for dry lamination of film to paper, board and packaging substrates, with technical documentation where applicable.":["تأمین چسب پایه آب برای لمینیشن خشک فیلم روی کاغذ، مقوا و بسترهای بسته‌بندی، همراه با مستندات فنی در صورت وجود.","توريد مواد لاصقة مائية للتصفيح الجاف بين الأفلام والورق والكرتون ومواد التغليف، مع الوثائق الفنية عند توفرها."],
"Specification-led sourcing of packaging materials for printers, converters and manufacturers through international procurement programs.":["تأمین مشخصات‌محور مواد بسته‌بندی برای چاپخانه‌ها، مبدل‌ها و تولیدکنندگان از طریق برنامه‌های خرید بین‌المللی.","توريد مواد تغليف وفق المواصفات للطابعين والمحوّلين والمصنعين من خلال برامج مشتريات دولية."],
"View A4 specifications":["مشاهده مشخصات A4","عرض مواصفات A4"],"View film specifications":["مشاهده مشخصات فیلم","عرض مواصفات الأفلام"],"View adhesive specifications":["مشاهده مشخصات چسب","عرض مواصفات المواد اللاصقة"],"View packaging materials":["مشاهده مواد بسته‌بندی","عرض مواد التغليف"],"Scientific product guide":["راهنمای علمی محصول","الدليل العلمي للمنتج"],"Add to cart":["افزودن به سبد","أضف إلى السلة"],"Cart:":["سبد:","السلة:"],"· View order":["· مشاهده سفارش","· عرض الطلب"],
"Need more technical information?":["اطلاعات فنی بیشتری نیاز دارید؟","هل تحتاج إلى مزيد من المعلومات الفنية؟"],"Visit the SEC PACK Knowledge Center for deeper material and application guidance. If you have a technical question, send it to us and our team can respond online.":["برای راهنمایی عمیق‌تر درباره مواد و کاربردها به مرکز دانش SEC PACK مراجعه کنید. اگر سؤال فنی دارید، آن را برای ما ارسال کنید تا تیم ما پاسخ دهد.","زر مركز معرفة SEC PACK للحصول على إرشادات أعمق حول المواد والتطبيقات. إذا كان لديك سؤال فني، أرسله إلينا ليجيب فريقنا عبر الإنترنت."],"Go to Knowledge Center →":["رفتن به مرکز دانش →","الانتقال إلى مركز المعرفة →"],"Ask a technical question →":["پرسش فنی →","طرح سؤال فني →"],
"International sourcing built around real procurement requirements.":["تأمین بین‌المللی بر پایه نیازهای واقعی خرید.","التوريد الدولي المبني على احتياجات المشتريات الفعلية."],"Start a business discussion":["شروع گفت‌وگوی تجاری","بدء مناقشة تجارية"],"For manufacturers & export partners":["برای تولیدکنندگان و شرکای صادراتی","للمصنعين وشركاء التصدير"],"WHAT WE DO":["ما چه می‌کنیم","ماذا نفعل"],"A practical bridge between demand and supply.":["پل عملی میان تقاضا و عرضه.","حلقة وصل عملية بين الطلب والعرض."],"Source":["تأمین","التوريد"],"Evaluate":["ارزیابی","التقييم"],"Coordinate":["هماهنگی","التنسيق"],"Identify suitable manufacturers and export partners against product, quality, packaging, quantity and destination requirements.":["تولیدکنندگان و شرکای صادراتی مناسب را بر اساس محصول، کیفیت، بسته‌بندی، مقدار و مقصد شناسایی می‌کنیم.","نحدد المصنعين وشركاء التصدير المناسبين وفق متطلبات المنتج والجودة والتغليف والكمية والوجهة."],"Compare technical specifications, documentation, production capability, commercial terms and practical delivery considerations.":["مشخصات فنی، مستندات، توان تولید، شرایط تجاری و ملاحظات عملی تحویل را مقایسه می‌کنیم.","نقارن المواصفات الفنية والوثائق والقدرة الإنتاجية والشروط التجارية واعتبارات التسليم العملية."],"Structure RFQs, clarify specifications, support negotiation and coordinate the purchasing process through agreed commercial terms.":["استعلام‌های قیمت را ساختاربندی، مشخصات را شفاف، مذاکرات را پشتیبانی و فرایند خرید را بر اساس شرایط توافق‌شده هماهنگ می‌کنیم.","ننظم طلبات عروض الأسعار، ونوضح المواصفات، وندعم التفاوض، وننسق عملية الشراء وفق الشروط التجارية المتفق عليها."],
"HOW WE CREATE VALUE":["چگونه ارزش ایجاد می‌کنیم","كيف نصنع القيمة"],"Requirement-led procurement, with fewer assumptions.":["خرید مبتنی بر نیاز، با حداقل فرضیات.","مشتريات قائمة على المتطلبات، مع أقل قدر من الافتراضات."],"Start with the application":["از کاربرد شروع کنید","ابدأ بالتطبيق"],"Compare on like-for-like terms":["مقایسه بر مبنای شرایط هم‌سطح","قارن على أساس متكافئ"],"Confirm before commitment":["پیش از تعهد تأیید کنید","أكد قبل الالتزام"],
"OUR WORKFLOW":["فرایند کاری ما","آلية عملنا"],"Clear requirements. Documented decisions.":["نیازهای روشن. تصمیم‌های مستند.","متطلبات واضحة. قرارات موثقة."],"Requirement and application":["نیاز و کاربرد","المتطلب والتطبيق"],"Supplier and product screening":["غربالگری تأمین‌کننده و محصول","فحص المورد والمنتج"],"Technical and commercial review":["بررسی فنی و تجاری","المراجعة الفنية والتجارية"],"Quotation, terms and delivery planning":["برنامه‌ریزی قیمت، شرایط و تحویل","التخطيط للعرض والشروط والتسليم"],"Order coordination and documentation":["هماهنگی سفارش و مستندات","تنسيق الطلب والوثائق"],
"BUSINESS PRINCIPLES":["اصول کسب‌وکار","مبادئ العمل"],"What partners can expect.":["آنچه شرکا می‌توانند انتظار داشته باشند.","ما يمكن للشركاء توقعه."],"Specification discipline":["انضباط در مشخصات","الانضباط في المواصفات"],"Commercial clarity":["شفافیت تجاری","الوضوح التجاري"],"Confidentiality by design":["محرمانگی از ابتدا","السرية بحكم التصميم"],"Long-term supply":["تأمین بلندمدت","التوريد طويل الأجل"],"Clear specifications":["مشخصات شفاف","مواصفات واضحة"],"Professional procurement":["خرید حرفه‌ای","مشتريات احترافية"],"Long-term cooperation":["همکاری بلندمدت","تعاون طويل الأمد"],
"FOR MANUFACTURERS · EXPORT PARTNERS":["برای تولیدکنندگان · شرکای صادراتی","للمصنعين · شركاء التصدير"],"A structured route to long-term B2B supply.":["مسیر ساختاریافته برای تأمین بلندمدت B2B.","مسار منظم للتوريد طويل الأجل في قطاع B2B."],"Discuss cooperation":["گفت‌وگوی همکاری","ناقش التعاون"],"Company profile":["معرفی شرکت","نبذة عن الشركة"],"WHAT AN EXPORT TEAM CAN EXPECT":["انتظارات از تیم صادرات","ما يمكن لفريق التصدير توقعه"],"A clear commercial brief before detailed discussion.":["شرح تجاری روشن پیش از گفت‌وگوی جزئی.","موجز تجاري واضح قبل المناقشة التفصيلية."],"Defined demand":["تقاضای مشخص","طلب محدد"],"Technical review":["بررسی فنی","مراجعة فنية"],"Commercial coordination":["هماهنگی تجاری","تنسيق تجاري"],"WHAT WE LOOK FOR":["آنچه به دنبال آن هستیم","ما نبحث عنه"],"Capability, documentation and communication that support a serious export relationship.":["توانمندی، مستندات و ارتباطی که از یک رابطه صادراتی جدی پشتیبانی کند.","قدرة ووثائق وتواصل يدعم علاقة تصدير جادة."],"Product fit":["تناسب محصول","ملاءمة المنتج"],"Supply capability":["توان تأمین","قدرة التوريد"],"Documentation":["مستندات","الوثائق"],"HOW WE WORK":["چگونه کار می‌کنیم","كيف نعمل"],"A structured first conversation saves time.":["یک گفت‌وگوی اولیه ساختاریافته در زمان صرفه‌جویی می‌کند.","المحادثة الأولى المنظمة توفر الوقت."],"CURRENT PRODUCT AREAS":["حوزه‌های فعلی محصول","مجالات المنتجات الحالية"],"Opportunities across paper and packaging materials.":["فرصت‌ها در حوزه کاغذ و مواد بسته‌بندی.","فرص في الورق ومواد التغليف."],"COMMERCIAL DISCIPLINE":["انضباط تجاری","الانضباط التجاري"],"We confirm the details before commitment.":["پیش از تعهد، جزئیات را تأیید می‌کنیم.","نؤكد التفاصيل قبل الالتزام."],"EXPORT SALES":["فروش صادراتی","مبيعات التصدير"],"Send your product and export proposal.":["پیشنهاد محصول و صادرات خود را ارسال کنید.","أرسل عرض المنتج والتصدير الخاص بك."],
"SPECIFICATION":["مشخصات","المواصفات"],"Built around the buyer's actual requirement.":["بر پایه نیاز واقعی خریدار.","مبني على متطلبات المشتري الفعلية."],"Core specification":["مشخصات اصلی","المواصفات الأساسية"],"Application":["کاربرد","التطبيق"],"Format / process":["فرمت / فرایند","التنسيق / العملية"],"Technical requirement":["نیاز فنی","المتطلب الفني"],"Supply program":["برنامه تأمین","برنامج التوريد"],"PROCUREMENT":["خرید","المشتريات"],"What we need to quote accurately.":["اطلاعات لازم برای قیمت‌گذاری دقیق.","ما نحتاجه لتقديم عرض دقيق."],"Technical specification":["مشخصات فنی","المواصفات الفنية"],"Quantity and packaging":["مقدار و بسته‌بندی","الكمية والتغليف"],"Destination and delivery terms":["مقصد و شرایط تحویل","الوجهة وشروط التسليم"],"Commercial and documentation requirements":["النیازهای تجاری و مستنداتی","المتطلبات التجارية والوثائق"],"START A SUPPLY REQUEST":["شروع درخواست تأمین","ابدأ طلب التوريد"],"Need this product for a B2B program?":["این محصول را برای برنامه B2B نیاز دارید؟","هل تحتاج هذا المنتج لبرنامج B2B؟"],"Request a quotation":["درخواست قیمت","طلب عرض سعر"],"Request / Order":["درخواست / سفارش","طلب / طلب شراء"],"Discuss specifications":["گفت‌وگوی مشخصات","مناقشة المواصفات"],
"ONLINE SUPPLY CENTER":["مرکز تأمین آنلاین","مركز التوريد عبر الإنترنت"],"Prepare a B2B order request online.":["درخواست سفارش B2B را آنلاین آماده کنید.","جهّز طلب شراء B2B عبر الإنترنت."],"Select products and quantities here. This is an inquiry-preparation tool, not a live payment checkout; final price, availability, specifications and delivery terms are confirmed directly by SEC PACK.":["محصولات و مقدار را اینجا انتخاب کنید. این ابزار برای آماده‌سازی درخواست است، نه پرداخت آنلاین؛ قیمت نهایی، موجودی، مشخصات و شرایط تحویل مستقیماً توسط SEC PACK تأیید می‌شود.","اختر المنتجات والكميات هنا. هذه أداة لإعداد الطلب وليست للدفع المباشر؛ يتم تأكيد السعر النهائي والتوفر والمواصفات وشروط التسليم مباشرة من SEC PACK."],"Order-ready supply categories":["دسته‌های آماده سفارش","فئات التوريد الجاهزة للطلب"],"Add to order":["افزودن به سفارش","أضف إلى الطلب"],"Film solutions for paper and board lamination":["راهکارهای فیلم برای لمینیشن کاغذ و مقوا","حلول أفلام لتصفيح الورق والكرتون"],"Dry-lamination applications · TDS/COA where applicable":["کاربردهای لمینیشن خشک · TDS/COA در صورت وجود","تطبيقات التصفيح الجاف · TDS/COA عند توفرها"],"Specification-led sourcing for converters and manufacturers":["تأمین مشخصات‌محور برای مبدل‌ها و تولیدکنندگان","توريد وفق المواصفات للمحوّلين والمصنعين"],"Your online order":["سفارش آنلاین شما","طلبك عبر الإنترنت"],"Final quotation:":["قیمت نهایی:","عرض السعر النهائي:"],"SEC PACK will confirm price, availability, specifications, delivery terms and payment method before order acceptance.":["SEC PACK پیش از پذیرش سفارش، قیمت، موجودی، مشخصات، شرایط تحویل و روش پرداخت را تأیید می‌کند.","ستؤكد SEC PACK السعر والتوفر والمواصفات وشروط التسليم وطريقة الدفع قبل قبول الطلب."],"Preferred payment method":["روش پرداخت ترجیحی","طريقة الدفع المفضلة"],"Bank transfer":["حواله بانکی","تحويل مصرفي"],"Local online payment":["پرداخت آنلاین محلی","دفع محلي عبر الإنترنت"],"International payment":["پرداخت بین‌المللی","دفع دولي"],"Prepare order request":["آماده‌سازی درخواست سفارش","إعداد طلب الشراء"],"B2B CHECKOUT":["ثبت سفارش B2B","إتمام طلب B2B"],"Online ordering, with commercial confirmation.":["سفارش آنلاین، با تأیید تجاری.","الطلب عبر الإنترنت مع تأكيد تجاري."],
"CONTACT SEC PACK":["تماس با SEC PACK","اتصل بـ SEC PACK"],"Start with your exact requirement.":["از نیاز دقیق خود شروع کنید.","ابدأ بمتطلباتك الدقيقة."],"For a useful first discussion, provide the product, application, specification, approximate quantity and target market.":["برای یک گفت‌وگوی اولیه مفید، محصول، کاربرد، مشخصات، مقدار تقریبی و بازار هدف را اعلام کنید.","لبدء مناقشة مفيدة، اذكر المنتج والتطبيق والمواصفات والكمية التقريبية والسوق المستهدف."],"WHAT TO INCLUDE":["چه اطلاعاتی وارد کنیم","ما الذي يجب تضمينه"],"A clear brief gets a clearer sourcing response.":["شرح روشن، پاسخ تأمین روشن‌تری ایجاد می‌کند.","الموجز الواضح يؤدي إلى استجابة توريد أوضح."],"Product and application":["محصول و کاربرد","المنتج والتطبيق"],"Required quantity and packaging":["مقدار موردنیاز و بسته‌بندی","الكمية والتغليف المطلوبان"],"Destination market and timing":["بازار مقصد و زمان‌بندی","سوق الوجهة والجدول الزمني"],"Name":["نام","الاسم"],"Product / Requirement":["محصول / نیاز","المنتج / المتطلب"],"Message":["پیام","الرسالة"],"Prepare Inquiry":["آماده‌سازی درخواست","إعداد الاستفسار"],"BUSINESS COOPERATION":["همکاری تجاری","التعاون التجاري"],"What makes an inquiry commercially useful?":["چه چیزی یک درخواست را از نظر تجاری مفید می‌کند؟","ما الذي يجعل الاستفسار مفيدًا تجاريًا؟"],"Buyers":["خریداران","المشترون"],"Manufacturers":["تولیدکنندگان","المصنعون"],"Confidentiality":["محرمانگی","السرية"],"B2B COOPERATION":["همکاری B2B","تعاون B2B"],"Looking for a manufacturer or supply partner?":["به دنبال تولیدکننده یا شریک تأمین هستید؟","هل تبحث عن مصنع أو شريك توريد؟"],
"Privacy & Data Handling":["حریم خصوصی و مدیریت داده","الخصوصية ومعالجة البيانات"],"Public privacy information for SEC PACK website visitors and B2B inquiries.":["اطلاعات عمومی حریم خصوصی برای بازدیدکنندگان سایت و درخواست‌های B2B.","معلومات الخصوصية العامة لزوار موقع SEC PACK واستفسارات B2B."],"PUBLIC WEBSITE":["وب‌سایت عمومی","الموقع العام"],"Designed to minimize unnecessary data exposure.":["طراحی‌شده برای کاهش افشای غیرضروری داده‌ها.","مصمم لتقليل كشف البيانات غير الضروري."],"Public website":["وب‌سایت عمومی","الموقع العام"],"Local browser data":["داده‌های محلی مرورگر","بيانات المتصفح المحلية"],"Confidential business data":["داده‌های محرمانه تجاری","بيانات الأعمال السرية"],"Future ordering":["سفارش‌دهی آینده","الطلبات المستقبلية"],"Terms of Use":["شرایط استفاده","شروط الاستخدام"],"General website and B2B supply request terms for SEC PACK.":["شرایط عمومی استفاده از وب‌سایت و درخواست تأمین B2B برای SEC PACK.","الشروط العامة للموقع وطلبات التوريد B2B لدى SEC PACK."],"Clear expectations for product and sourcing inquiries.":["انتظارات روشن برای درخواست‌های محصول و تأمین.","توقعات واضحة لاستفسارات المنتجات والتوريد."],"Product information":["اطلاعات محصول","معلومات المنتج"],"Quotations":["قیمت‌ها و پیشنهادهای تجاری","عروض الأسعار"],"Third-party services":["خدمات شخص ثالث","خدمات الأطراف الثالثة"],"Accuracy":["دقت اطلاعات","دقة المعلومات"],
"SEC PACK KNOWLEDGE CENTER":["مرکز دانش SEC PACK","مركز معرفة SEC PACK"],"Practical knowledge for better sourcing and purchasing decisions.":["دانش کاربردی برای تصمیم‌های بهتر در تأمین و خرید.","معرفة عملية لاتخاذ قرارات أفضل في التوريد والشراء."],"Independent-style educational content from SEC PACK covering product specifications, supplier evaluation and international procurement. Commercial offers are always confirmed separately.":["محتوای آموزشی مستقل‌گونه SEC PACK درباره مشخصات محصول، ارزیابی تأمین‌کننده و خرید بین‌المللی. پیشنهادهای تجاری همیشه جداگانه تأیید می‌شوند.","محتوى تعليمي من SEC PACK حول مواصفات المنتجات وتقييم الموردين والمشتريات الدولية. يتم دائمًا تأكيد العروض التجارية بشكل منفصل."],"A4 COPY PAPER":["کاغذ تحریر A4","ورق نسخ A4"],"75 GSM vs 80 GSM: what actually changes?":["75 گرم در برابر 80 گرم: چه چیزی واقعاً تغییر می‌کند؟","75 مقابل 80 غ/م²: ما الذي يتغير فعليًا؟"],"Weight":["وزن","الوزن"],"Handling":["نحوه کار و جابه‌جایی","المناولة"],"Printer performance":["عملکرد چاپگر","أداء الطابعة"],"SUPPLIER EVALUATION":["ارزیابی تأمین‌کننده","تقييم المورد"],"A professional RFQ should define the product before asking for price.":["یک RFQ حرفه‌ای باید پیش از درخواست قیمت، محصول را دقیق تعریف کند.","يجب أن يحدد طلب عرض السعر المهني المنتج قبل طلب السعر."],"Technical specification":["مشخصات فنی","المواصفات الفنية"],"Commercial specification":["مشخصات تجاری","المواصفات التجارية"],"Evidence":["شواهد و مستندات","الأدلة"],"LANDED COST":["هزینه نهایی تحویل","التكلفة النهائية عند الوصول"],"Factory price is not the same as delivered cost.":["قیمت کارخانه با هزینه تحویل‌شده یکسان نیست.","سعر المصنع ليس هو نفسه تكلفة التسليم."],"Product":["محصول","المنتج"],"Origin logistics":["لجستیک مبدأ","لوجستيات المنشأ"],"International transport":["حمل‌ونقل بین‌المللی","النقل الدولي"],"Destination":["مقصد","الوجهة"],"LAMINATION & ADHESIVES":["لمینیشن و چسب‌ها","التصفيح والمواد اللاصقة"],"Specification checklist before requesting a quotation.":["چک‌لیست مشخصات پیش از درخواست قیمت.","قائمة تحقق للمواصفات قبل طلب عرض السعر."],"Lamination film":["فیلم لمینیشن","فيلم التصفيح"],"Water-based adhesive":["چسب پایه آب","المادة اللاصقة المائية"],"FAQ":["سؤالات متداول","الأسئلة الشائعة"],"Common procurement questions":["پرسش‌های رایج خرید","أسئلة المشتريات الشائعة"],"75 GSM or 80 GSM?":["75 گرم یا 80 گرم؟","75 أم 80 غ/م²؟"],"How should suppliers be compared?":["تأمین‌کنندگان چگونه مقایسه شوند؟","كيف تتم مقارنة الموردين؟"],"Why request samples?":["چرا نمونه درخواست کنیم؟","لماذا نطلب عينات؟"],"What makes a long-term supply program?":["چه چیزی یک برنامه تأمین بلندمدت می‌سازد؟","ما الذي يجعل برنامج التوريد طويل الأجل ناجحًا؟"],"USE THE KNOWLEDGE":["از دانش استفاده کنید","استخدم المعرفة"],"Have a specific sourcing requirement?":["نیاز مشخصی برای تأمین دارید؟","هل لديك متطلب توريد محدد؟"],"Discuss a requirement":["گفت‌وگوی درباره نیاز","ناقش متطلبًا"],
"HOW WE WORK":["چگونه کار می‌کنیم","كيف نعمل"],"Practical information for a disciplined procurement process.":["اطلاعات کاربردی برای فرایند خرید منظم و دقیق.","معلومات عملية لعملية مشتريات منضبطة."],"Product Specifications":["مشخصات محصول","مواصفات المنتج"],"Technical Documentation":["مستندات فنی","الوثائق الفنية"],"Supplier Evaluation":["ارزیابی تأمین‌کننده","تقييم المورد"],"RFQ Preparation":["آماده‌سازی RFQ","إعداد طلب عرض السعر"],"Quality Review":["بررسی کیفیت","مراجعة الجودة"],"Procurement Workflow":["فرایند خرید","سير عمل المشتريات"],
"Register for Technical Updates":["ثبت‌نام برای دریافت اطلاعات فنی","التسجيل للحصول على التحديثات الفنية"],"Register your business profile":["ثبت اطلاعات حرفه‌ای","تسجيل ملفك المهني"],"Register and stay connected":["ثبت‌نام و ارتباط با SEC PACK","سجّل وابقَ على تواصل"],"Register for technical solutions and new product updates.":["برای راهکارهای فنی و محصولات جدید ثبت‌نام کنید.","سجّل للحصول على الحلول الفنية وتحديثات المنتجات الجديدة."],"Tell us a little about your professional activity. We will share useful technical information and, if you choose, relevant new products and business updates.":["کمی درباره فعالیت حرفه‌ای خود بگویید. اطلاعات فنی کاربردی و در صورت تمایل محصولات و به‌روزرسانی‌های تجاری مرتبط را با شما به اشتراک می‌گذاریم.","أخبرنا قليلًا عن نشاطك المهني. سنشاركك معلومات فنية مفيدة، وإذا اخترت، منتجات جديدة وتحديثات تجارية ذات صلة."],"Full name":["نام و نام خانوادگی","الاسم الكامل"],"Company":["شرکت","الشركة"],"Country / City":["کشور / شهر","الدولة / المدينة"],"Job title":["عنوان شغلی","المسمى الوظيفي"],"Business activity":["فعالیت کسب‌وکار","نشاط الأعمال"],"Product / technical interest":["محصول / زمینه فنی موردنظر","المنتج / الاهتمام الفني"],"Mobile / WhatsApp":["موبایل / واتساپ","الجوال / واتساب"],"Email":["ایمیل","البريد الإلكتروني"],"Company website":["وب‌سایت شرکت","موقع الشركة"],"Message / requirement":["پیام / نیاز","الرسالة / المتطلب"],"I agree to receive technical information, new product updates and relevant business messages from SEC PACK by email, WhatsApp or SMS.":["موافقم اطلاعات فنی، محصولات جدید و پیام‌های تجاری مرتبط SEC PACK را از طریق ایمیل، واتساپ یا پیامک دریافت کنم.","أوافق على تلقي المعلومات الفنية وتحديثات المنتجات الجديدة والرسائل التجارية ذات الصلة من SEC PACK عبر البريد الإلكتروني أو واتساب أو الرسائل النصية."],"Privacy Policy":["سیاست حفظ حریم خصوصی","سياسة الخصوصية"],"Close":["بستن","إغلاق"]
};


// Product-page technical copy
Object.assign(D,{
"Request / Order":["درخواست / سفارش","طلب / طلب شراء"],"Discuss specifications":["گفت‌وگو درباره مشخصات","مناقشة المواصفات"],"Built around the buyer's actual requirement.":["بر پایه نیاز واقعی خریدار.","مبني على متطلبات المشتري الفعلية."],"For a commercial quotation, send the required specification, quantity, destination, packaging preference, target timing and any compliance or documentation requirements. Equivalent alternatives should be identified explicitly rather than assumed.":["برای دریافت قیمت تجاری، مشخصات موردنیاز، مقدار، مقصد، نوع بسته‌بندی، زمان‌بندی و الزامات انطباق یا مستندات را ارسال کنید. گزینه‌های جایگزین باید صریحاً مشخص شوند و نباید فرض شوند.","للحصول على عرض تجاري، أرسل المواصفات والكمية والوجهة ونوع التغليف والجدول الزمني وأي متطلبات امتثال أو وثائق. يجب تحديد البدائل بوضوح وعدم افتراضها."],
"Need this product for a B2B program?":["این محصول را برای یک برنامه B2B نیاز دارید؟","هل تحتاج هذا المنتج لبرنامج B2B؟"],"Submit your requirement and SEC PACK can structure it for supplier comparison and commercial discussion.":["نیاز خود را ارسال کنید تا SEC PACK آن را برای مقایسه تأمین‌کنندگان و گفت‌وگوی تجاری ساختاربندی کند.","أرسل متطلباتك ويمكن لـ SEC PACK تنظيمها لمقارنة الموردين والمناقشة التجارية."],"Request a quotation":["درخواست قیمت","طلب عرض سعر"],
"Core specification":["مشخصات اصلی","المواصفات الأساسية"],"Format / process":["فرمت / فرایند","التنسيق / العملية"],"Supply program":["برنامه تأمین","برنامج التوريد"],"Documentation":["مستندات","الوثائق"],"Technical requirement":["نیاز فنی","المتطلب الفني"],"Application":["کاربرد","التطبيق"],
"75–80 GSM":["75–80 گرم در مترمربع","75–80 غ/م²"],"210 × 297 mm":["210 × 297 میلی‌متر","210 × 297 مم"],"500 sheets / ream":["500 برگ / ریم","500 ورقة / رزمة"],"5 reams / carton":["5 ریم / کارتن","5 رزم / كرتون"],"Virgin / wood pulp specifications":["مشخصات خمیر بکر / چوب","مواصفات لب الخشب البكر"],"OEM / private label where available":["OEM / برند اختصاصی در صورت امکان","OEM / علامة خاصة عند توفرها"],
"SPECIFICATION":["مشخصات","المواصفات"],"PROCUREMENT":["خرید و تأمین","المشتريات والتوريد"],"START A SUPPLY REQUEST":["شروع درخواست تأمین","ابدأ طلب التوريد"],
"75–80 GSM programs":["برنامه‌های 75–80 گرم","برامج 75–80 غ/م²"],"OEM and private-label supply options.":["گزینه‌های تأمین OEM و برند اختصاصی.","خيارات توريد OEM والعلامة الخاصة."],
"B2B sourcing for BOPP, PET and MPET lamination films for paper, board, printing and packaging applications.":["تأمین B2B فیلم‌های لمینیشن BOPP، PET و MPET برای کاغذ، مقوا، چاپ و بسته‌بندی.","توريد B2B لأفلام التصفيح BOPP وPET وMPET لتطبيقات الورق والكرتون والطباعة والتغليف."],
"Specification-led sourcing for BOPP, PET and MPET films used in printing, finishing, paper and board lamination and packaging applications.":["تأمین مشخصات‌محور فیلم‌های BOPP، PET و MPET برای چاپ، تکمیل، لمینیشن کاغذ و مقوا و بسته‌بندی.","توريد وفق المواصفات لأفلام BOPP وPET وMPET المستخدمة في الطباعة والتشطيب وتصفيح الورق والكرتون والتغليف."],
"BOPP / PET / MPET":["BOPP / PET / MPET","BOPP / PET / MPET"],"Application-specific":["متناسب با کاربرد","وفق التطبيق"],"Roll format":["فرمت رول","صيغة اللفة"],"Width and thickness":["عرض و ضخامت","العرض والسماكة"],"Surface treatment":["عملیات سطحی","معالجة السطح"],"Industrial converting":["تبدیل و کانورتینگ صنعتی","التحويل الصناعي"],
"Water-based adhesive sourcing for paper, film and board lamination. Requirements are matched to substrates, coating method, drying conditions, line speed and required bond performance.":["تأمین چسب پایه آب برای لمینیشن کاغذ، فیلم و مقوا؛ نیازها بر اساس بستر، روش پوشش‌دهی، شرایط خشک‌شدن، سرعت خط و عملکرد چسبندگی موردنیاز تطبیق داده می‌شوند.","توريد مواد لاصقة مائية لتصفيح الورق والأفلام والكرتون؛ تتم مطابقة المتطلبات مع الركائز وطريقة الطلاء وظروف التجفيف وسرعة الخط وأداء الالتصاق المطلوب."],
"Water-based adhesive sourcing for dry lamination of film to paper, board and packaging substrates, with technical documentation where applicable.":["تأمین چسب پایه آب برای لمینیشن خشک فیلم روی کاغذ، مقوا و بسترهای بسته‌بندی، همراه با مستندات فنی در صورت وجود.","توريد مواد لاصقة مائية للتصفيح الجاف بين الأفلام والورق والكرتون ومواد التغليف، مع الوثائق الفنية عند توفرها."],
"Water-based":["پایه آب","مائي"],"Paper / film / board":["کاغذ / فیلم / مقوا","ورق / فيلم / كرتون"],"Substrate compatibility":["سازگاری با بستر","توافق الركيزة"],"Coating method":["روش پوشش‌دهی","طريقة الطلاء"],"Drying conditions":["شرایط خشک‌شدن","ظروف التجفيف"],"TDS / COA where applicable":["TDS / COA در صورت وجود","TDS / COA عند توفرها"],
"Specification-led sourcing for printers, converters and packaging manufacturers, with product selection based on application, quality, commercial and delivery requirements.":["تأمین مشخصات‌محور برای چاپخانه‌ها، مبدل‌ها و تولیدکنندگان بسته‌بندی؛ انتخاب محصول بر اساس کاربرد، کیفیت، الزامات تجاری و تحویل انجام می‌شود.","توريد وفق المواصفات للطابعين والمحوّلين ومصنعي التغليف؛ يتم اختيار المنتج بناءً على التطبيق والجودة والمتطلبات التجارية والتسليم."],
"Application-specific":["متناسب با کاربرد","وفق التطبيق"],"Printer / converter / manufacturer":["چاپخانه / مبدل / تولیدکننده","طابع / محوّل / مصنع"],"Technical specification":["مشخصات فنی","المواصفات الفنية"],"Packaging format":["فرمت بسته‌بندی","صيغة التغليف"],"Quantity program":["برنامه مقداری","برنامج الكمية"],"Long-term supply":["تأمین بلندمدت","توريد طويل الأجل"],
"International sourcing, procurement and trade support for professional B2B customers.":["تأمین بین‌المللی، خرید و پشتیبانی تجارت برای مشتریان حرفه‌ای B2B.","التوريد الدولي والمشتريات ودعم التجارة للعملاء المحترفين في قطاع B2B."]
});
function translateNode(el,lang){
 const raw=(el.textContent||"").replace(/\s+/g," ").trim();
 if(!raw)return;
 if(!el.hasAttribute("data-original-text")) el.setAttribute("data-original-text",raw);
 if(lang==="en"){ el.textContent=el.getAttribute("data-original-text"); return; }
 const v=D[el.getAttribute("data-original-text")||raw];
 if(v && v[lang==="fa"?0:1]) el.textContent=v[lang==="fa"?0:1];
}

function applyExact(lang){
 document.documentElement.lang=lang;
 document.documentElement.dir=(lang==="fa"||lang==="ar")?"rtl":"ltr";
 document.querySelectorAll("[data-lang]").forEach(b=>{
   b.classList.toggle("on",b.dataset.lang===lang);
   b.classList.toggle("active-language",b.dataset.lang===lang);
 });
 document.querySelectorAll("body *").forEach(el=>{
   if(el.children.length===0) translateNode(el,lang);
 });
 if(window.applyPageTranslations) window.applyPageTranslations(lang);
 localStorage.setItem(KEY,lang);
}

const PAGE_TEXT={
"company.html":{
"SEC PACK works with professional buyers, manufacturers and export partners to structure product requirements, evaluate supply options and coordinate practical B2B procurement.":["SEC PACK با خریداران حرفه‌ای، تولیدکنندگان و شرکای صادراتی برای ساختاربندی نیاز محصول، ارزیابی گزینه‌های تأمین و هماهنگی خرید B2B همکاری می‌کند.","تعمل SEC PACK مع المشترين المحترفين والمصنعين وشركاء التصدير لتحديد متطلبات المنتجات وتقييم خيارات التوريد وتنسيق مشتريات B2B."],
"Our public-facing work is centered on clearly specified products and dependable commercial coordination—not on publishing confidential supplier or pricing information.":["فعالیت عمومی ما بر محصولات با مشخصات روشن و هماهنگی تجاری قابل اتکا متمرکز است، نه انتشار اطلاعات محرمانه تأمین‌کنندگان یا قیمت‌ها.","يركز عملنا العام على المنتجات ذات المواصفات الواضحة والتنسيق التجاري الموثوق، وليس نشر معلومات الموردين أو الأسعار السرية."],
"Selected materials for printing, packaging and converting.":["مواد منتخب برای چاپ، بسته‌بندی و کانورتینگ." ,"مواد مختارة للطباعة والتغليف والتحويل."],
"75–80 GSM programs, OEM/private label where available.":["برنامه‌های ۷۵ تا ۸۰ گرم، OEM/برند اختصاصی در صورت امکان.","برامج 75–80 غ/م²، مع OEM/العلامة الخاصة عند توفرها."],
"BOPP, PET and MPET solutions for professional applications.":["راهکارهای BOPP، PET و MPET برای کاربردهای حرفه‌ای.","حلول BOPP وPET وMPET للتطبيقات المهنية."],
"Paper, film and board lamination applications.":["کاربردهای لمینیشن کاغذ، فیلم و مقوا.","تطبيقات تصفيح الورق والأفلام والكرتون."],
"Specification-led sourcing for converters and manufacturers.":["تأمین مشخصات‌محور برای مبدل‌ها و تولیدکنندگان.","توريد وفق المواصفات للمحوّلين والمصنعين."],
"SEC PACK is designed around a simple principle: the right supplier is only useful when the product, specification, commercial terms and delivery route fit the actual requirement.":["SEC PACK بر یک اصل ساده بنا شده است: تأمین‌کننده مناسب زمانی ارزشمند است که محصول، مشخصات، شرایط تجاری و مسیر تحویل با نیاز واقعی هماهنگ باشد.","تقوم SEC PACK على مبدأ بسيط: يكون المورد المناسب مفيدًا عندما يتوافق المنتج والمواصفات والشروط التجارية ومسار التسليم مع المتطلب الفعلي."],
"We clarify what the material must do before comparing offers.":["پیش از مقایسه پیشنهادها، مشخص می‌کنیم ماده موردنظر باید چه عملکردی داشته باشد.","نحدد الوظيفة المطلوبة من المادة قبل مقارنة العروض."],
"Specifications, packaging, quantity, documentation and delivery conditions are considered together.":["مشخصات، بسته‌بندی، مقدار، مستندات و شرایط تحویل در کنار هم بررسی می‌شوند.","تتم دراسة المواصفات والتغليف والكمية والوثائق وشروط التسليم معًا."],
"Commercial and technical details are documented before an order is accepted.":["جزئیات تجاری و فنی پیش از پذیرش سفارش مستند می‌شوند.","يتم توثيق التفاصيل التجارية والفنية قبل قبول الطلب."],
"For each commercial opportunity, the objective is to reduce ambiguity before an order is accepted.":["در هر فرصت تجاری، هدف کاهش ابهام پیش از پذیرش سفارش است.","في كل فرصة تجارية، الهدف هو تقليل الغموض قبل قبول الطلب."],
"We prefer measurable specifications and written confirmation rather than assumptions or vague product descriptions.":["مشخصات قابل اندازه‌گیری و تأیید کتبی را به جای فرضیات یا توصیف‌های مبهم ترجیح می‌دهیم.","نفضل المواصفات القابلة للقياس والتأكيد الكتابي بدلًا من الافتراضات أو الأوصاف الغامضة."],
"Prices, availability, payment terms, delivery terms and final specifications are confirmed before commercial acceptance.":["قیمت، موجودی، شرایط پرداخت، شرایط تحویل و مشخصات نهایی پیش از پذیرش تجاری تأیید می‌شوند.","يتم تأكيد الأسعار والتوفر وشروط الدفع والتسليم والمواصفات النهائية قبل القبول التجاري."],
"Private supplier identities, purchase prices, margins and internal procurement records are not published on the public website.":["هویت خصوصی تأمین‌کنندگان، قیمت‌های خرید، حاشیه سود و سوابق داخلی خرید در وب‌سایت عمومی منتشر نمی‌شوند.","لا يتم نشر هويات الموردين الخاصة وأسعار الشراء وهوامش الربح وسجلات المشتريات الداخلية على الموقع العام."],
"We are interested in repeatable supply programs and practical manufacturer relationships, not only one-off inquiries.":["ما به برنامه‌های تأمین تکرارشونده و روابط عملی با تولیدکنندگان علاقه‌مندیم، نه فقط درخواست‌های موردی.","نهتم ببرامج التوريد المتكررة والعلاقات العملية مع المصنعين، وليس فقط بالطلبات الفردية."],
"Have a product, market or supply opportunity?":["فرصتی در محصول، بازار یا تأمین دارید؟","لديك فرصة في منتج أو سوق أو توريد؟"],
"Send the requirement or supplier proposal with the relevant technical and commercial information.":["نیاز یا پیشنهاد تأمین‌کننده را همراه با اطلاعات فنی و تجاری مرتبط ارسال کنید.","أرسل المتطلب أو عرض المورد مع المعلومات الفنية والتجارية ذات الصلة."]
},
"manufacturers.html":{
"SEC PACK works with manufacturers and export teams through defined specifications, transparent commercial discussions and practical supply planning. The objective is to build repeatable relationships where product fit and supply capability are clear.":["SEC PACK با تولیدکنندگان و تیم‌های صادراتی بر پایه مشخصات تعریف‌شده، گفت‌وگوی تجاری شفاف و برنامه‌ریزی عملی تأمین همکاری می‌کند. هدف، ایجاد روابط تکرارشونده‌ای است که تناسب محصول و توان تأمین در آنها روشن باشد.","تعمل SEC PACK مع المصنعين وفرق التصدير وفق مواصفات محددة ومناقشات تجارية شفافة وتخطيط عملي للتوريد. الهدف هو بناء علاقات متكررة تكون فيها ملاءمة المنتج وقدرة التوريد واضحة."],
"We aim to make the first exchange useful for both sides: the manufacturer sees the actual requirement, while SEC PACK can evaluate the offer against defined criteria.":["هدف ما این است که نخستین تبادل اطلاعات برای هر دو طرف مفید باشد: تولیدکننده نیاز واقعی را می‌بیند و SEC PACK می‌تواند پیشنهاد را بر اساس معیارهای مشخص ارزیابی کند.","نسعى إلى جعل التواصل الأول مفيدًا للطرفين: يرى المصنع المتطلب الفعلي، بينما تستطيع SEC PACK تقييم العرض وفق معايير محددة."],
"Product application, specification, quantity, packaging and destination are clarified as the opportunity develops.":["کاربرد محصول، مشخصات، مقدار، بسته‌بندی و مقصد هم‌زمان با پیشرفت فرصت تجاری روشن می‌شوند.","يتم توضيح تطبيق المنتج والمواصفات والكمية والتغليف والوجهة مع تطور الفرصة."],
"Samples, TDS, COA and other relevant documentation can be reviewed where applicable.":["نمونه‌ها، TDS، COA و سایر مستندات مرتبط در صورت امکان بررسی می‌شوند.","يمكن مراجعة العينات وTDS وCOA والوثائق ذات الصلة عند توفرها."],
"MOQ, lead time, packaging, payment and delivery terms are discussed before purchasing commitment.":["MOQ، زمان تولید، بسته‌بندی، پرداخت و شرایط تحویل پیش از تعهد خرید بررسی می‌شوند.","تتم مناقشة MOQ ومدة الإنتاج والتغليف والدفع وشروط التسليم قبل الالتزام بالشراء."],
"Clear technical specifications, application knowledge and consistent product identification.":["مشخصات فنی روشن، شناخت کاربرد و شناسایی ثابت محصول.","مواصفات فنية واضحة ومعرفة بالتطبيق وتحديد متسق للمنتج."],
"Realistic production capacity, lead times, packaging options and export readiness.":["ظرفیت واقعی تولید، زمان تحویل، گزینه‌های بسته‌بندی و آمادگی صادراتی.","قدرة إنتاج واقعية ومهل توريد وخيارات تغليف وجاهزية للتصدير."],
"Technical data, quality information, certificates or test documentation where applicable.":["اطلاعات فنی، کیفیت، گواهی‌ها یا مستندات آزمون در صورت وجود.","البيانات الفنية ومعلومات الجودة والشهادات أو وثائق الاختبار عند توفرها."],
"When introducing a product, please provide the information needed for a commercial and technical review.":["هنگام معرفی محصول، اطلاعات لازم برای بررسی تجاری و فنی را ارائه کنید.","عند تقديم منتج، يرجى توفير المعلومات اللازمة للمراجعة التجارية والفنية."],
"Manufacturer / factory identity and export contact":["هویت تولیدکننده / کارخانه و تماس صادراتی","هوية المصنع / الشركة وجهة اتصال التصدير"],
"Product catalogue and technical specifications":["کاتالوگ محصول و مشخصات فنی","كتالوج المنتج والمواصفات الفنية"],
"MOQ, production lead time and packaging options":["MOQ، زمان تولید و گزینه‌های بسته‌بندی","MOQ ومدة الإنتاج وخيارات التغليف"],
"Available delivery terms and destination support":["شرایط تحویل موجود و پشتیبانی مقصد","شروط التسليم المتاحة ودعم الوجهة"],
"OEM / private-label capability, if available":["توان OEM / برند اختصاصی در صورت وجود","إمكانية OEM / العلامة الخاصة عند توفرها"],
"Public categories include A4 copy paper, lamination films, water-based adhesives and packaging materials. Product-specific opportunities depend on the buyer requirement and market.":["دسته‌های عمومی شامل کاغذ A4، فیلم‌های لمینیشن، چسب‌های پایه آب و مواد بسته‌بندی هستند. فرصت‌های هر محصول به نیاز خریدار و بازار بستگی دارد.","تشمل الفئات العامة ورق A4 وأفلام التصفيح والمواد اللاصقة المائية ومواد التغليف. وتعتمد فرص كل منتج على متطلبات المشتري والسوق."],
"Website content is informational. Final specifications, pricing, availability, payment, delivery terms and order acceptance are confirmed directly for each transaction.":["محتوای وب‌سایت اطلاع‌رسانی است. مشخصات نهایی، قیمت، موجودی، پرداخت، شرایط تحویل و پذیرش سفارش برای هر معامله مستقیماً تأیید می‌شوند.","محتوى الموقع معلوماتي. يتم تأكيد المواصفات النهائية والأسعار والتوفر والدفع وشروط التسليم وقبول الطلب مباشرة لكل معاملة."],
"Include your catalogue, technical data, MOQ, lead time, packaging and preferred contact channel.":["کاتالوگ، اطلاعات فنی، MOQ، زمان تحویل، بسته‌بندی و کانال ارتباطی ترجیحی خود را ارسال کنید.","أرفق الكتالوج والبيانات الفنية وMOQ ومدة التوريد والتغليف وقناة الاتصال المفضلة."]
},
"documents.html":{
"Information that supports better material selection.":["اطلاعاتی برای انتخاب بهتر مواد.","معلومات تساعد على اختيار المواد بشكل أفضل."],
"Public resources are designed to help customers understand specifications, applications and the procurement process.":["منابع عمومی برای کمک به درک مشخصات، کاربردها و فرایند خرید طراحی شده‌اند.","صممت الموارد العامة لمساعدة العملاء على فهم المواصفات والتطبيقات وعملية الشراء."],
"SEC PACK uses clear specifications and documented communication to reduce ambiguity between buyers, manufacturers and export partners.":["SEC PACK برای کاهش ابهام میان خریداران، تولیدکنندگان و شرکای صادراتی از مشخصات روشن و ارتباطات مستند استفاده می‌کند.","تستخدم SEC PACK مواصفات واضحة وتواصلًا موثقًا لتقليل الغموض بين المشترين والمصنعين وشركاء التصدير."],
"Define dimensions, GSM, substrate, application, packaging and quality requirements before requesting quotations.":["پیش از درخواست قیمت، ابعاد، GSM، بستر، کاربرد، بسته‌بندی و الزامات کیفیت را مشخص کنید.","حدد المقاسات وGSM والركيزة والتطبيق والتغليف ومتطلبات الجودة قبل طلب عروض الأسعار."],
"TDS, COA and relevant quality documentation can be requested as part of product evaluation where applicable.":["TDS، COA و مستندات کیفی مرتبط را می‌توان در چارچوب ارزیابی محصول درخواست کرد.","يمكن طلب TDS وCOA ووثائق الجودة ذات الصلة ضمن تقييم المنتج عند الحاجة."],
"Manufacturer identity, production capability, export experience, references and sample performance should be reviewed together.":["هویت تولیدکننده، توان تولید، تجربه صادرات، سوابق و عملکرد نمونه باید در کنار هم بررسی شوند.","ينبغي مراجعة هوية المصنع وقدرته الإنتاجية وخبرته التصديرية ومراجعه وأداء العينات معًا."],
"A precise RFQ reduces ambiguity and makes quotations easier to compare on a like-for-like basis.":["یک RFQ دقیق ابهام را کاهش می‌دهد و مقایسه قیمت‌ها را بر مبنای شرایط یکسان آسان‌تر می‌کند.","يقلل RFQ الدقيق الغموض ويسهّل مقارنة العروض على أساس متكافئ."],
"Material selection should consider the real production process and end-use requirements, not only nominal specifications.":["انتخاب مواد باید فرایند واقعی تولید و نیاز مصرف نهایی را در نظر بگیرد، نه فقط مشخصات اسمی.","ينبغي أن يراعي اختيار المواد عملية الإنتاج الفعلية ومتطلبات الاستخدام النهائي، وليس المواصفات الاسمية فقط."],
"Requirement → sourcing → supplier screening → quotation → sample/technical review → commercial coordination.":["نیاز → تأمین → غربالگری تأمین‌کننده → قیمت‌گذاری → بررسی نمونه/فنی → هماهنگی تجاری","المتطلب → التوريد → فحص المورد → عرض السعر → مراجعة العينة/الفنية → التنسيق التجاري"]
},
"contact.html":{
"A supplier or buyer can save time by including the exact product, specification, quantity, packaging, destination, expected timing and relevant documentation requirements.":["تأمین‌کننده یا خریدار با ارائه دقیق محصول، مشخصات، مقدار، بسته‌بندی، مقصد، زمان مورد انتظار و مستندات لازم می‌تواند در زمان صرفه‌جویی کند.","يمكن للمورد أو المشتري توفير الوقت من خلال تحديد المنتج والمواصفات والكمية والتغليف والوجهة والموعد المتوقع والوثائق المطلوبة بدقة."],
"Send your requirement in measurable terms so suitable supply options can be compared.":["نیاز خود را با معیارهای قابل اندازه‌گیری ارسال کنید تا گزینه‌های مناسب تأمین قابل مقایسه باشند.","أرسل متطلباتك بمصطلحات قابلة للقياس لتتم مقارنة خيارات التوريد المناسبة."],
"Send factory identity, catalogue, technical data, MOQ, lead time and export terms.":["هویت کارخانه، کاتالوگ، اطلاعات فنی، MOQ، زمان تحویل و شرایط صادرات را ارسال کنید.","أرسل هوية المصنع والكتالوج والبيانات الفنية وMOQ ومدة التوريد وشروط التصدير."],
"Do not send passwords, payment credentials or other sensitive information through this public form.":["رمز عبور، اطلاعات پرداخت یا سایر اطلاعات حساس را از طریق این فرم عمومی ارسال نکنید.","لا ترسل كلمات المرور أو بيانات الدفع أو أي معلومات حساسة أخرى عبر هذا النموذج العام."],
"SEC PACK can structure the requirement for sourcing and supplier discussions.":["SEC PACK می‌تواند نیاز شما را برای تأمین و گفت‌وگو با تأمین‌کنندگان ساختاربندی کند.","يمكن لـ SEC PACK تنظيم المتطلب لمناقشات التوريد والموردين."]
},
"privacy.html":{
"Public privacy information for SEC PACK website visitors and B2B inquiries.":["اطلاعات عمومی حریم خصوصی برای بازدیدکنندگان وب‌سایت SEC PACK و درخواست‌های B2B.","معلومات الخصوصية العامة لزوار موقع SEC PACK واستفسارات B2B."],
"This website is primarily a public product, sourcing and educational site. The current static storefront does not process card payments and does not transmit customer form data to a server.":["این وب‌سایت عمدتاً یک سایت عمومی محصولات، تأمین و آموزش است. فروشگاه استاتیک فعلی پرداخت کارتی انجام نمی‌دهد و اطلاعات فرم مشتری را به سرور ارسال نمی‌کند.","هذا الموقع أساسًا موقع عام للمنتجات والتوريد والمحتوى التعليمي. المتجر الثابت الحالي لا يعالج مدفوعات البطاقات ولا يرسل بيانات النماذج إلى خادم."],
"The storefront may keep a temporary cart draft in the visitor's browser. Customer contact details entered in the current static form are not persisted by the site.":["فروشگاه ممکن است پیش‌نویس موقت سبد را در مرورگر بازدیدکننده نگه دارد. اطلاعات تماس واردشده در فرم استاتیک فعلی توسط سایت ذخیره نمی‌شود.","قد يحتفظ المتجر بمسودة مؤقتة للسلة في متصفح الزائر. ولا يتم حفظ بيانات الاتصال المدخلة في النموذج الثابت الحالي."],
"Supplier identities, purchase prices, target margins, private logistics information, internal procurement records, credentials and other confidential business information are intentionally excluded from the public website.":["هویت تأمین‌کنندگان، قیمت‌های خرید، حاشیه سود هدف، اطلاعات لجستیکی خصوصی، سوابق داخلی خرید، اطلاعات ورود و سایر داده‌های محرمانه عمداً از وب‌سایت عمومی حذف شده‌اند.","تم استبعاد هويات الموردين وأسعار الشراء وهوامش الربح المستهدفة ومعلومات اللوجستيات الخاصة وسجلات المشتريات الداخلية وبيانات الدخول والمعلومات التجارية السرية عمدًا من الموقع العام."],
"When a production order and payment backend are connected, data handling, retention and payment-provider terms will be documented before that service is activated.":["هنگام اتصال سامانه سفارش و پرداخت واقعی، نحوه پردازش و نگهداری داده و شرایط ارائه‌دهنده پرداخت پیش از فعال‌سازی مستند خواهد شد.","عند ربط نظام الطلب والدفع الفعلي، سيتم توثيق معالجة البيانات والاحتفاظ بها وشروط مزود الدفع قبل تفعيل الخدمة."]
},
"terms.html":{
"General website and B2B supply request terms for SEC PACK.":["شرایط عمومی وب‌سایت و درخواست تأمین B2B برای SEC PACK.","الشروط العامة للموقع وطلبات التوريد B2B لدى SEC PACK."],
"Public product pages describe typical requirements and sourcing categories. Final specifications, availability, commercial terms and delivery conditions are confirmed for each transaction.":["صفحات عمومی محصول نیازهای معمول و دسته‌های تأمین را توضیح می‌دهند. مشخصات نهایی، موجودی، شرایط تجاری و تحویل برای هر معامله تأیید می‌شوند.","تصف صفحات المنتجات العامة المتطلبات المعتادة وفئات التوريد. ويتم تأكيد المواصفات النهائية والتوفر والشروط التجارية والتسليم لكل معاملة."],
"A website inquiry or cart draft is not, by itself, acceptance of an order or a binding commercial quotation. SEC PACK confirms applicable terms before order acceptance.":["درخواست وب‌سایت یا پیش‌نویس سبد به‌تنهایی پذیرش سفارش یا پیشنهاد تجاری الزام‌آور محسوب نمی‌شود. SEC PACK شرایط قابل اعمال را پیش از پذیرش سفارش تأیید می‌کند.","لا يُعد استفسار الموقع أو مسودة السلة بحد ذاته قبولًا للطلب أو عرضًا تجاريًا ملزمًا. تؤكد SEC PACK الشروط المعمول بها قبل قبول الطلب."],
"Future payment, shipping, analytics or communication services may have their own terms and privacy policies. They will be identified when actually integrated.":["خدمات آینده پرداخت، حمل، تحلیل یا ارتباطات ممکن است شرایط و سیاست‌های حریم خصوصی خود را داشته باشند. هنگام ادغام واقعی معرفی خواهند شد.","قد تكون لخدمات الدفع أو الشحن أو التحليلات أو الاتصالات المستقبلية شروط وسياسات خصوصية خاصة بها، وسيتم تحديدها عند دمجها فعليًا."],
"Product specifications and educational content should be reviewed against the final commercial specification, technical documentation and applicable destination requirements.":["مشخصات محصول و محتوای آموزشی باید با مشخصات تجاری نهایی، مستندات فنی و الزامات مقصد بررسی شوند.","ينبغي مراجعة مواصفات المنتجات والمحتوى التعليمي مقابل المواصفات التجارية النهائية والوثائق الفنية ومتطلبات الوجهة المعمول بها."]
},
"store.html":{
"Prepare a B2B order request online.":["درخواست سفارش B2B را آنلاین آماده کنید.","جهّز طلب شراء B2B عبر الإنترنت."],
"Select products and quantities here. This is an inquiry-preparation tool, not a live payment checkout; final price, availability, specifications and delivery terms are confirmed directly by SEC PACK.":["محصولات و مقدار را اینجا انتخاب کنید. این ابزار برای آماده‌سازی درخواست است، نه پرداخت آنلاین؛ قیمت نهایی، موجودی، مشخصات و شرایط تحویل مستقیماً توسط SEC PACK تأیید می‌شود.","اختر المنتجات والكميات هنا. هذه أداة لإعداد الطلب وليست للدفع المباشر؛ يتم تأكيد السعر النهائي والتوفر والمواصفات وشروط التسليم مباشرة من SEC PACK."],
"210 × 297 mm · 500 sheets/ream · 5 reams/carton":["۲۱۰ × ۲۹۷ میلی‌متر · ۵۰۰ برگ/ریم · ۵ ریم/کارتن","210 × 297 مم · 500 ورقة/رزمة · 5 رزم/كرتون"],
"Film solutions for paper and board lamination":["راهکارهای فیلم برای لمینیشن کاغذ و مقوا","حلول أفلام لتصفيح الورق والكرتون"],
"Dry-lamination applications · TDS/COA where applicable":["کاربردهای لمینیشن خشک · TDS/COA در صورت وجود","تطبيقات التصفيح الجاف · TDS/COA عند توفرها"],
"Specification-led sourcing for converters and manufacturers":["تأمین مشخصات‌محور برای مبدل‌ها و تولیدکنندگان","توريد وفق المواصفات للمحوّلين والمصنعين"],
"We keep the checkout practical: you submit the order online, then SEC PACK confirms the commercial terms before payment or dispatch.":["فرایند سفارش را عملی نگه می‌داریم: درخواست را آنلاین ارسال می‌کنید و SEC PACK پیش از پرداخت یا ارسال، شرایط تجاری را تأیید می‌کند.","نبقي عملية الطلب عملية: ترسل الطلب عبر الإنترنت ثم تؤكد SEC PACK الشروط التجارية قبل الدفع أو الشحن."],
"Your order is empty.":["سفارش شما خالی است.","طلبك فارغ."],
"Order prepared.":["سفارش آماده شد.","تم إعداد الطلب."],
"Your cart draft is kept only for this browser session; customer contact details are not stored by the static site. The next production step is connecting this checkout to SEC PACK's confirmed order/payment endpoint.":["پیش‌نویس سبد فقط برای همین نشست مرورگر نگهداری می‌شود؛ اطلاعات تماس مشتری توسط سایت استاتیک ذخیره نمی‌شود. مرحله بعدی اتصال این فرایند به سامانه تأییدشده سفارش/پرداخت SEC PACK است.","يتم الاحتفاظ بمسودة السلة لهذه الجلسة فقط؛ ولا يحفظ الموقع الثابت بيانات اتصال العميل. والخطوة التالية هي ربط الطلب بنظام الطلب/الدفع المعتمد لدى SEC PACK."]
},
"products.html":{
"Materials selected for professional printing, packaging and converting.":["مواد منتخب برای چاپ، بسته‌بندی و کانورتینگ حرفه‌ای.","مواد مختارة للطباعة والتغليف والتحويل الاحترافي."],
"SEC PACK develops its portfolio around clear specifications, industrial applications and dependable supply.":["SEC PACK سبد محصولات خود را بر اساس مشخصات روشن، کاربردهای صنعتی و تأمین قابل اتکا توسعه می‌دهد.","تطوّر SEC PACK محفظتها حول المواصفات الواضحة والتطبيقات الصناعية والتوريد الموثوق."],
"A4 cut-size office paper for professional supply programs.":["کاغذ اداری برش‌خورده A4 برای برنامه‌های حرفه‌ای تأمین.","ورق مكتبي A4 مقصوص لبرامج التوريد الاحترافية."],
"OEM & private-label programs where available":["برنامه‌های OEM و برند اختصاصی در صورت امکان","برامج OEM والعلامة الخاصة عند توفرها"],
"Film solutions for printing, finishing and packaging applications.":["راهکارهای فیلم برای چاپ، تکمیل و بسته‌بندی.","حلول أفلام للطباعة والتشطيب والتغليف."],
"BOPP / PET / MPET applications":["کاربردهای BOPP / PET / MPET","تطبيقات BOPP / PET / MPET"],
"Paper and board lamination":["لمینیشن کاغذ و مقوا","تصفيح الورق والكرتون"],
"Industrial converting requirements":["نیازهای کانورتینگ صنعتی","متطلبات التحويل الصناعي"],
"Specification-led sourcing":["تأمین مشخصات‌محور","التوريد وفق المواصفات"],
"Water-based adhesive solutions for paper, film and board lamination processes.":["راهکارهای چسب پایه آب برای فرایندهای لمینیشن کاغذ، فیلم و مقوا.","حلول لاصقة مائية لعمليات تصفيح الورق والأفلام والكرتون."],
"Technical data review":["بررسی اطلاعات فنی","مراجعة البيانات الفنية"],
"Process-oriented evaluation":["ارزیابی فرایندمحور","تقييم قائم على العملية"],
"COA / TDS documentation where applicable":["مستندات COA / TDS در صورت وجود","وثائق COA / TDS عند توفرها"],
"Selected materials for printers, converters and packaging manufacturers.":["مواد منتخب برای چاپخانه‌ها، مبدل‌ها و تولیدکنندگان بسته‌بندی.","مواد مختارة للطابعين والمحوّلين ومصنعي التغليف."],
"Application-specific sourcing":["تأمین متناسب با کاربرد","توريد وفق التطبيق"],
"Manufacturer identification":["شناسایی تولیدکننده","تحديد المصنع"],
"Commercial specification matching":["تطبیق مشخصات تجاری","مطابقة المواصفات التجارية"],
"Long-term supply programs":["برنامه‌های تأمین بلندمدت","برامج التوريد طويلة الأجل"],
"Need more technical information?":["اطلاعات فنی بیشتری نیاز دارید؟","هل تحتاج إلى مزيد من المعلومات الفنية؟"],
"Visit the SEC PACK Knowledge Center for deeper material and application guidance. If you have a technical question, send it to us and our team can respond online.":["برای راهنمایی عمیق‌تر درباره مواد و کاربردها به مرکز دانش SEC PACK مراجعه کنید. اگر سؤال فنی دارید، آن را برای ما ارسال کنید تا تیم ما پاسخ دهد.","زر مركز معرفة SEC PACK للحصول على إرشادات أعمق حول المواد والتطبيقات. إذا كان لديك سؤال فني، أرسله إلينا ليجيب فريقنا عبر الإنترنت."]
}
};
function applyPageTranslations(lang){
 const path=(location.pathname||"").toLowerCase(); const file=Object.keys(PAGE_TEXT).find(k=>path.endsWith(k));
 if(file&&lang!=="en"){document.querySelectorAll("body *").forEach(el=>{if(el.children.length===0){const t=(el.textContent||"").trim();const v=PAGE_TEXT[file][t];if(v)el.textContent=v[lang==="fa"?0:1];}});}
 const oldFile=path.endsWith("lamination-films.html")?"lamination-films.html":path.endsWith("water-based-adhesives.html")?"water-based-adhesives.html":null;
 if(oldFile&&lang!=="en"){const m=oldFile==="lamination-films.html"?{fa:["فیلم‌های لمینیشن","تأمین B2B فیلم‌های لمینیشن BOPP، PET و MPET برای کاغذ، مقوا، چاپ و بسته‌بندی."],ar:["أفلام التصفيح","توريد B2B لأفلام BOPP وPET وMPET لتطبيقات الورق والكرتون والطباعة والتغليف."]}:{fa:["چسب‌های پایه آب","تأمین چسب پایه آب برای لمینیشن خشک فیلم روی کاغذ، مقوا و بسترهای بسته‌بندی، همراه با مستندات فنی در صورت وجود."],ar:["مواد لاصقة مائية","توريد مواد لاصقة مائية للتصفيح الجاف بين الأفلام والورق والكرتون ومواد التغليف، مع الوثائق الفنية عند توفرها."]};const v=m[lang];document.querySelector(".page-hero h1")&&(document.querySelector(".page-hero h1").textContent=v[0]);document.querySelector(".page-hero>p")&&(document.querySelector(".page-hero>p").textContent=v[1]);}
}
function setLanguage(lang){
 lang=SUPPORTED.includes(lang)?lang:"en";
 applyExact(lang);
 applyPageTranslations(lang);
 if(typeof window.setHomepageLanguage==="function") window.setHomepageLanguage(lang);
}
function init(){
 document.querySelectorAll("[data-lang]").forEach(btn=>{
   btn.addEventListener("click",()=>setLanguage(btn.dataset.lang));
 });
 setLanguage(localStorage.getItem(KEY)||"en");
}
window.secpackSetLanguage=setLanguage;
if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",init,{once:true}); else init();
})();