-- Compatibility marker.
-- Idempotency columns are now part of the baseline schema and are therefore
-- created deterministically on fresh databases. Existing deployments keep
-- their historical migration record; no runtime schema mutation is required.
