-- Compatibility marker.
-- unit_cost_minor is now part of the baseline commerce schema. Existing
-- deployments retain this migration in their history; schema ownership lives
-- in migrations rather than request-time ALTER TABLE operations.
